#!/usr/bin/env bash

usage() {
cat << END
Usage: $0 [option] <filename>
  option:
    -h show help message
    -n show line number
      
END
}

if [[ $# -lt 1 ]]; then 
  usage
  exit 1
fi

while getopts ":n" opt; do 
  case "$opt" in
    n) lineNum=TRUE;;
    *) usage
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

var=1
cat $1 | while read line; do
  if [[ $lineNum == TRUE ]]; then
    echo "$((var++)). $line"
  else 
    echo "$line"
  fi
done
