#!/usr/bin/env bash

usage() {
cat << END
Usage: $0 [option] <url>
  option:
    -h show help message
    -f save links into a file

END
}

saveLinksToFile() {
  wget -qO- $1 | grep -oP 'href=\"http.*?"' | awk -F\" '{ print $2 }'> ./links
}

printLinksToConsole() {
  wget -qO- $1 | grep -oP 'href=\"http.*?"' | awk -F\" '{ print $2 }'
}

if [[ $1 == '-h' ]]; then
  usage
  exit 0
fi

if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then 
  usage
  exit 1
fi 

 
if [[ $1 == '-f' ]]; then
  saveLinksToFile "$2"   
elif [[ $2 == '-f' ]]; then
  saveLinksToFile "$1"
else
  printLinksToConsole "$1" 
fi

