#!/usr/bin/env bash

saveLinksToFile() {
  wget -qO- $1 | grep -oP 'href=\".*?"' | awk -F\" '{ print $2 }'> ./links
}

printLinksToConsole() {
  wget -qO- $1 | grep -oP 'href=\".*?"' | awk -F\" '{ print $2 }'
}

if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then 
  echo "usage: $0 [-f] url"
  exit 1
fi 

 
if [[ $1 == '-f' ]]; then
  saveLinksToFile "$2"   
elif [[ $2 == '-f' ]]; then
  saveLinksToFile "$1"
else
  printLinksToConsole "$1" 
fi

